version: 2

jobs:
  build_and_push_master:
    machine: true
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            ./build.sh latest
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ictu/cloud-config-server

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push_master:
          filters:
            branches:
              only: master